### ISSUE TITLE
Large plots don't show when called from IPython's `interact` 

### ISSUE THREAD

**Issue by dela3499** [twosigma/beakerx#2809] opened 2015-10-23 22:35 UTC
In trying to plot a dataframe with around 50,000 rows, I used IPython's interact function to add some widgets in my analysis. I found the plotting behaved very oddly in my experiments. Here are some of my observations:
1. Calling `f` directly to plot the data below always works - the plot is shown below the code cell.
2. Calling `f` from `interact` works best when there are fewer points
   - always works when n < 20,000
   - seldom works when n > 30,000
   - there's hysteresis in the following sequence, and intermittent success with n = 30,000
     - n = 40,000 # fail (no plot shown)
     - n = 30,000 # fail
     - n = 10,000 # success
     - n = 30,000 # success

I've never seen this sort of behavior, so I'm not sure what to make of it. 

``` python
import IPython.html.widgets as widgets
from IPython.html.widgets import interact

np.random.seed(123)
n = 30000
x = np.random.random(n)
y = np.random.random(n)
def f():
    plt.plot(x,y,'ro')

interact(f) # sometimes shows plot, almost always for n < 20,000, and almost never for n > 30,000
f() # always shows plot
```

**Comment by scottdraves** [comment] 2015-10-23 22:46
thanks for the report.  i think there is a race condition in there somewhere we also got this report: https://github.com/twosigma/beaker-notebook/issues/2467
i tried your code and again could not repro, even with 100k points.

**Comment by dela3499** [comment] 2015-10-23 22:51
Another observation. If I generate a small dataset within `f`, and then use a widget to increase its size, I don't run into the problem above. But, if I start out with a large dataset, no plot or widget is shown. I take it that the race condition you mentioned is only a problem on the initialization of the widget?

``` python
import IPython.html.widgets as widgets
from IPython.html.widgets import interact

np.random.seed(123)
def f(n):
    x = np.random.random(n)
    y = np.random.random(n)
    plt.plot(x,y,'ro')

# If initial value is low (~20), n can be raised up to 50,000.
# If initial value is high (~40,000), no plot or widget is shown
interact(f,n = widgets.IntSlider(min = 1, max = 50000, step = 200, value = 20)) 

# f(50000) # always shows plot
```

**Comment by dela3499** [comment] 2015-10-23 22:53
I'm running an R kernel as well, if that changes anything. Are there any logs or additional information I can provide to help debug this?

**Comment by scottdraves** [comment] 2015-10-23 23:16
Is there anything suspicious on the JavaScript console?
What OS do you have?

**Comment by dela3499** [comment] 2015-10-23 23:47
I'm running Chrome on Ubuntu 14.04, and nothing's logged to console when I run the examples above.

**Comment by dela3499** [comment] 2015-10-24 00:03
Since initialization seems problematic, I'm running `interact` with an on/off widget that starts in the off position. This seems to work well. Once the widget is shown, I check the box that turns my plot on, and everything works as it should. 

``` python
import IPython.html.widgets as widgets
from IPython.html.widgets import interact

def f(show,alpha):
    if show:
        n = 100000
        x = np.random.random(n)
        y = np.random.random(n)
        plt.plot(x,y,'ro', alpha = alpha)

# widget starts with show = False, then you can click checkbox to show plot
# widget doesn't work when initialized with show = True
interact(
    f,
    show = True,
    alpha = widgets.FloatSlider(
        min = 0, 
        max = 0.1, 
        step = 0.01, 
        value = 0.01))
```

**Comment by scottdraves** [comment] 2015-10-24 00:59
thanks that could be a good clue.

**Comment by dela3499** [comment] 2015-10-27 01:01
Another observation here. When I plot and then wait a short while, it seems to work normally. But, if the sleep time is set a bit high, the plot isn't shown to screen.

``` python
def plotx():
    n = 1000
    delay = 0.15 # works for low delays (0.01) and fails for large ones (0.1)
    x = np.random.random(n)
    y = np.random.random(n)
    plt.plot(x,y)
    time.sleep(delay)
interact(plotx)
```

**Comment by alice-kroch** [comment] 2015-10-29 15:58
@dela3499, please, test this [dist](https://dl.dropboxusercontent.com/u/16000016/dist.zip)

**Comment by scottdraves** [comment] 2015-10-29 16:06
Hi, Carlos, Alice has a proposed fix for this issue.  however since i was unable to reproduce it, i can't really test it.  could you please see how it works for you?  it's a zip file for ubuntu, at the link above.

**Comment by dela3499** [comment] 2015-10-29 19:24
@alice-kroch Tested it. Works perfectly in all the cases above! :+1:

**Closed as completed** 2015-10-30 14:36 UTC
Labels: Bug, Kernel
