### ISSUE TITLE
UI options not working in jupyter lab

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#7735] opened 2018-08-02 18:04 UTC
when i open the options panel i get errors like
```
Uncaught (in promise) TypeError: e is not iterable
    at d.onLoad (vendors~main.5f50933161d709d44097.js:131)
    at r.update (vendors~main.5f50933161d709d44097.js:131)
    at o.update (vendors~main.5f50933161d709d44097.js:131)
    at api.loadSettings.then.e (vendors~main.5f50933161d709d44097.js:131)
```
and on each click
```
Uncaught TypeError: Cannot set property 'auto_save' of undefined
    at f.optionsChangedHandler (tree.js:13530)
    at HTMLInputElement.dispatch (tree.js:5334)
    at HTMLInputElement.m.handle (tree.js:5142)
```
they are not taking effect "autoclose brackets".

when i open a notebook there are some errors, idk if they mean anything:
```
codeEditor.js:23 Uncaught (in promise) TypeError: Cannot read property 'widgets' of undefined
    at Object.t.registerCommentOutCmd (codeEditor.js:23)
    at index.js:47
t.registerCommentOutCmd @ codeEditor.js:23
(anonymous) @ index.js:47
Promise.then (async)
e.createNew @ index.js:45
r.each.e @ widgetmanager.js:67
i @ iter.js:60
createWidget @ widgetmanager.js:66
_createOrOpenDocument @ manager.js:420
open @ manager.js:247
openOrReveal @ manager.js:271
_evtDblClick @ listing.js:892
handleEvent @ listing.js:539
default.js:1432 Kernel: connected (ebfc7837-50e9-4f2b-9dfa-26713a1379a1)
initializationCells.js:50 Uncaught (in promise) TypeError: Cannot read property 'widgets' of undefined
    at f (initializationCells.js:50)
    at u (initializationCells.js:39)
    at initializationCells.js:35
```

Jupyter Lab 0.32.1 and 0.33.4
BeakerX 1.0.0

**Comment by piorek** [comment] 2018-08-08 10:58
@scottdraves can't reproduce it, send me please the content of your beakerx.json file for further investigation. You can also try to remove it to see if that will help.

**Comment by piorek** [comment] 2018-10-19 10:49
@LeeTZ checked it again on current master. Cannot reproduce it. I think we can close this one.

**Closed as completed** 2018-12-03 05:46 UTC
