### ISSUE TITLE
Regression - NullPointerException in TableDisplay.java

### ISSUE THREAD

**Issue by benmccann** [twosigma/beakerx#6690] opened 2018-01-22 05:23 UTC
I recently updated my environment:
beakerx: 0.9.1-py35_0 conda-forge --> 0.11.1-py35_1 conda-forge

I'm now getting a `NullPointerException`

Sample code to reproduce:
```
sp500 = session.getDataSet(DataSetRequest.Builder.of("MULTPL/SP500_REAL_PRICE_MONTH").build());
sp500 = sp500.sortOn("Date")
sp500.addColumn(sp500.floatColumn("Value").rolling(10).mean())
```

Exception
>java.lang.NullPointerException
	at com.twosigma.beakerx.table.TableDisplay.<init>(TableDisplay.java:182)
	at com.twosigma.beakerx.table.TableDisplay.<init>(TableDisplay.java:135)
	at com.twosigma.beakerx.table.TableDisplay.<init>(TableDisplay.java:216)
	at tech.tablesaw.beakerx.TablesawDisplayer$1.display(TablesawDisplayer.java:34)
	at tech.tablesaw.beakerx.TablesawDisplayer$1.display(TablesawDisplayer.java:28)
	at jupyter.Displayers.display(Displayers.java:62)
	at com.twosigma.beakerx.SerializeToString.getMimeContainer(SerializeToString.java:84)
	at com.twosigma.beakerx.SerializeToString.doit(SerializeToString.java:46)
	at com.twosigma.beakerx.kernel.msg.MessageCreator.createFinishResult(MessageCreator.java:271)
	at com.twosigma.beakerx.kernel.msg.MessageCreator.createResultForSupportedStatus(MessageCreator.java:183)
	at com.twosigma.beakerx.kernel.msg.MessageCreator.createMessage(MessageCreator.java:173)
	at com.twosigma.beakerx.kernel.threads.ExecutionResultSender.update(ExecutionResultSender.java:47)
	at com.twosigma.beakerx.jvm.object.SimpleEvaluationObject.finished(SimpleEvaluationObject.java:81)
	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.run(GroovyCodeRunner.java:78

**Comment by scottdraves** [comment] 2018-01-22 12:39
Thanks we'll look into that

**Comment by scottdraves** [comment] 2018-01-22 15:23
Fixed on master now, with test to prevent regression.
Will have to decide if this means 0.11.2 or should just go with 0.12.0.

**Closed as completed** 2018-01-22 15:23 UTC

**Comment by benmccann** [comment] 2018-01-22 16:26
Thanks for the quick fix!

**Comment by benmccann** [comment] 2018-01-25 16:03
Thanks so much!

Any idea when a new release might be cut? This will be the biggest release ever for me given all the fixes in master currently - this one, the new Maven cell magic, and the fix for autozoom! So excited :-)

**Comment by scottdraves** [comment] 2018-01-25 16:08
no problem thanks for the report, we really appreciate it.
i decided since i am traveling at a workshop to skip 0.11.2 and just do 0.12.0 when I get back on monday, assuming the PRs for https://github.com/twosigma/beakerx/issues/6560 and https://github.com/twosigma/beakerx/issues/6712 go through.
