### ISSUE TITLE
bullets missing from html

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#2541] opened 2015-09-29 20:00 UTC
https://pub.beakernotebook.com/#/publications/560ad479-2640-44a4-9d42-be8a7ca6a383

**Comment by grin** [comment] 2015-09-30 14:16
should be fixed by: https://github.com/twosigma/bunsen/pull/1200

(couldn't test it with that specific notebook because it's no longer available)

**Comment by ildipo** [comment] 2015-10-01 14:11
not working

**Comment by grin** [comment] 2015-10-01 16:22
@ildipo  can you give an example where it's not working? Thanks.

**Comment by ildipo** [comment] 2015-10-01 16:37
https://pub.beakernotebook.com/#/publications/560b4726-ce94-4e2a-820a-8c828094e309?fullscreen=false

The list of demos and examples should have bullet points

**Comment by grin** [comment] 2015-10-01 17:12
In that particular example the issue is that those lists have incorrect syntax in the notebook source file, they both are missing parent `<ul>` or  `<ol>` elements. In my recent fix I changed list bullet styling in Publications to the default value, same as it is in Beaker: https://github.com/twosigma/bunsen/commit/7a1142309a96bf8aca12c5321e8077b95cfa1c37 
but I won't be able to use the same fix here because you can't style bullet points just for `<li>` elements.

Would fixing  html in the notebook source file be an option?

**Comment by scottdraves** [comment] 2015-10-01 17:15
yea give me a sec

**Comment by scottdraves** [comment] 2015-10-01 17:42
actually if i do that then the indentation in the HTML cell goes wrong.
so I think we should take this fix, and fix ul/li in Beaker and this tut later.
https://github.com/twosigma/beaker-notebook/issues/2582
once this is deployed i'll update the tutorial.

**Comment by ildipo** [comment] 2015-10-06 15:29
This has been deployed

**Closed as completed** 2015-10-06 15:29 UTC
Labels: Bug, Publications
