### ISSUE TITLE
bkr2ipynb breaks on nonascii chars

### ISSUE THREAD

**Issue by scottdraves** [twosigma/beakerx#5133] opened 2017-04-07 20:10 UTC
```
Traceback (most recent call last):
  File "/home/spot/.conda/envs/testx/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/spot/.conda/envs/testx/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/spot/.conda/envs/testx/lib/python3.5/site-packages/beakerx/bkr2ipynb.py", line 87, in <module>
    convertNotebook(notebook)
  File "/home/spot/.conda/envs/testx/lib/python3.5/site-packages/beakerx/bkr2ipynb.py", line 44, in convertNotebook
    data = json.load(data_file)
  File "/home/spot/.conda/envs/testx/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/home/spot/.conda/envs/testx/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6848: ordinal not in range(128)

```

**Comment by fishera123** [comment] 2017-04-10 09:59
couldn't reproduce UnicodeDecodeError, but I got another error while testing it. 
```
  File "/Users/ignite/anaconda3/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/ignite/anaconda3/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ignite/twosigma/convertor_test/bkr2ipynb.py", line 90, in <module>
    convertNotebook(notebook)
  File "/Users/ignite/twosigma/convertor_test/bkr2ipynb.py", line 48, in convertNotebook
    kernel_name = max(evaluators, key=evaluators.count)
ValueError: max() arg is an empty sequence
```
this one should be fixed in the pr

**Closed as completed** 2017-04-10 21:52 UTC
Labels: Bug
