### ISSUE TITLE
R backend fails when version > 3.1?

### ISSUE THREAD

**Issue by aolney** [twosigma/beakerx#3422] opened 2016-01-24 22:33 UTC
On Windows 10 Education, I tried latest beaker-notebook-1.5.1-0-g6e6bdd3-windows and electron version with R versions 3.2.3 and 3.2.1

In both cases I installed the recommended packages from R console using elevated prompt (as I have done with previous versions of Beaker), i.e.

```
install.packages('Rserve')
install.packages('ggplot2')
install.packages('devtools')
install.packages('RCurl')
install.packages('RJSONIO')
install.packages('jpeg')
install.packages('png')
install.packages('base64enc')
```

I also replicated this on a master branch install from May 2015

The result in all cases was the following error:

Latest version:

```
C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows>REM limitations under the License.
starting nginx instance (C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

Running
0: C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows\python\python
1: C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows/config/plugins/eval/r/rPlugin
2: 8804
Jan 24, 2016 10:22:39 AM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:8803: Software caused connection abort: recv failed
Jan 24, 2016 10:22:39 AM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:8803
Done starting R
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8804
R-stderr waiting over
R-stderr>Jan 24, 2016 10:22:41 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
R-stderr>SEVERE: exception starting RServe
R-stderr>org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
R-stderr>       at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:234)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:440)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:469)
```

master branch version (5/2015)

```
starting nginx instance (C:\Users\Andrew M Olney\Downloads\beaker-notebook\core/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

Running
0: C:\Users\Andrew M Olney\Downloads\beaker-notebook\core\python\python
1: C:\Users\Andrew M Olney\Downloads\beaker-notebook\core/config/plugins/eval/r/rPlugin
2: 8804
Done starting R
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8804
R-stderr waiting over
R-stderr>Jan 24, 2016 10:19:28 AM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
R-stderr>SEVERE: exception starting RServe
R-stderr>org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
R-stderr>       at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:234)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:431)
R-stderr>       at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:460)
```

Electron gave the same issue.

However, when I install R version 3.1.0 (and add C:\Program Files\R\R-3.1.0\bin\x64 to the PATH) then this test R code works:

```
hist(AirPassengers, 
     main="Histogram for Air Passengers", 
     xlab="Passengers", 
     border="blue", 
     col="green",
     xlim=c(100,700),
     las=1, 
     breaks=5)
```

With these messages in the latest 1.5 as mentioned above

```
C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows>REM limitations under the License.
starting nginx instance (C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

Running
0: C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows\python\python
1: C:\Users\Andrew M Olney\Downloads\beaker-notebook-1.5.1-0-g6e6bdd3-windows/config/plugins/eval/r/rPlugin
2: 8804
Jan 24, 2016 4:24:36 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {}->http://127.0.0.1:8803: Software caused connection abort: recv failed
Jan 24, 2016 4:24:36 PM org.apache.http.impl.execchain.RetryExec execute
INFO: Retrying request to {}->http://127.0.0.1:8803
Done starting R
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8804
R-stderr waiting over
```

and in the master branch as mentioned above

```
starting nginx instance (C:\Users\Andrew M Olney\Downloads\beaker-notebook\core/nginx)
[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8802

Connecting to http://127.0.0.1:8801/

Running
0: C:\Users\Andrew M Olney\Downloads\beaker-notebook\core\python\python
1: C:\Users\Andrew M Olney\Downloads\beaker-notebook\core/config/plugins/eval/r/rPlugin
2: 8804
Done starting R
R-stderr>[main] INFO org.eclipse.jetty.server.Server - jetty-8.1.13.v20130916
R-stderr>[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@127.0.0.1:8804
R-stderr waiting over
```

Though in the latest 1.5 Electron version, it errors out on the same example 

```
Error in plot.new() : cairo error 'error while writing to output stream'
```

Not sure if this is a version problem for R or perhaps a PATH problem since the new versions did not have directions to set PATH explicitly.

**Comment by scottdraves** [comment] 2016-01-24 22:54
thanks for the report, will review it tomorrow when i have access to my windows vm.

**Comment by bcaller** [comment] 2016-01-27 22:52
I also have problems with RServe on Windows, but with a different message. Not sure if it's related.

```
Jan 27, 2016 10:51:07 PM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused: connect
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:88)
    at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:431)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:469)
```

**Comment by scottdraves** [comment] 2016-01-27 23:10
@bcaller  did you install that package using the R command line?

**Comment by bcaller** [comment] 2016-01-27 23:40
I'd used the RGui (not RStudio). So I removed the packages, restarted and reinstalled from the command line and now I get what aolney had:

```
Jan 27, 2016 11:39:04 PM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:234)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:440)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:469)
```

**Comment by binnisb** [comment] 2016-01-28 11:17
I can also confirm this on Arch Linux, though I haven't tested previous versions of R (just installed for the first time) I get the same error with R 3.2.3.

``` bash
Jan 28, 2016 12:17:00 PM com.twosigma.beaker.r.utils.RServerEvaluator$workerThread startRserve
SEVERE: exception starting RServe
org.rosuda.REngine.Rserve.RserveException: eval failed, request status: error code: 127
    at org.rosuda.REngine.Rserve.RConnection.eval(RConnection.java:234)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.startRserve(RServerEvaluator.java:440)
    at com.twosigma.beaker.r.utils.RServerEvaluator$workerThread.run(RServerEvaluator.java:469)
```

**Comment by KnowledgeGarden** [comment] 2016-01-29 15:39
If this is closed, why am I seeing precisely the same error as binnish? What is missing here? What was changed to enable closing this issue?

**Comment by scottdraves** [comment] 2016-01-29 15:42
This issue is open.  Perhaps you are being confused because I closed #3439 because it is a duplicate of this one?

**Comment by KnowledgeGarden** [comment] 2016-01-29 15:43
Dopey me!
Really looking forward to bringing this puppy up! Lots of reasons for that.

**Comment by maxyeg** [comment] 2016-01-29 15:52
I confirm that R 3.2.3 doesn't work in master branch on Windows.
I saw errors when R plugin tries to evaluate init code and one of them was about missing package `roxygen2`.
After doing `install.packages('roxygen2')` error disappeared and R works well.
Please try this.

**Comment by KnowledgeGarden** [comment] 2016-01-29 16:03
That, indeed, worked. 
Side (possibly related?) observation:
ipython failed to load.
still, clicked the run button in the r demo, and got "null"
So, R did not work, perhaps because ipython wasn't working?

**Comment by amannj** [comment] 2016-01-29 16:07
@maxyeg great, this resolves the issue for me. 
(os: ubuntu gnome 15.10; beaker: version: 1.5.1-0-g6e6bdd3)

thanks everybody.

**Comment by gnaarrr** [comment] 2016-01-29 16:23
This also fixed it for me. (OSX El Capitan)

Thanks

**Comment by maxyeg** [comment] 2016-01-29 16:50
I'm not sure about IPython failure. Both R and IPython seem to work for me.
I've tried R demo and Python demo from the tutorials.
@KnowledgeGarden, maybe you could try to run Python demo and if it fails we could narrow root cause of the problem and it will be wrong python configuration?

**Comment by KnowledgeGarden** [comment] 2016-01-29 17:55
Good one!
trying in python27: ipython notebook got a message about no notebook installed. I note that in the breaker wiki, there is a difference in installation pip commands between py 2 and 3, where three says install ipython[notebook]/
trying in python34, where I did the pip3 install ipython[notebook] I get this error:
ImportError: No module named 'ipython_genutils'
Tried doing pip install --update ipython and got  the "already satisfied" message.
Went back to py27 and did pip install ipyton[notebook] and first got the "already satisfied" message, but it went ahead and installed the notebook. ipython notebook now runs.
But, breaker is still not able to start the notebook, with this error message:
ipython-hash-stderr>  File "C:\projects\SolrWatson\BeakerNotebookAPACHE\python\l
ib\os.py", line 344, in execvp
java.lang.RuntimeException: unable to get IPython hash
ipython-hash-stderr>    _execvpe(file, args)
        at com.twosigma.beaker.core.rest.PluginServiceLocatorRest.hashIPythonPas
sword(PluginServiceLocatorRest.java:609)ipython-hash-stderr>  File "C:\projects\
SolrWatson\BeakerNotebookAPACHE\python\lib\os.py", line 380, in _execvpe

**Comment by KnowledgeGarden** [comment] 2016-01-29 17:59
A more comprehensive stack trace is here:
https://gist.github.com/KnowledgeGarden/f6ec1e8c287299a8d709

**Comment by KnowledgeGarden** [comment] 2016-01-29 18:12
Observation: when I boot ipython notebook, I do not get what the tutorial says I should get. Instead, it goes to /tree which has a bunch of files listed. Three tabs: files, notebooks, and clusters. But, I do not see the notebook page itself where I have a New Notebook button.
I returned to python34, tried pip uninstall ipython.
Then pip install ipython
pip install --upgrade ipython[notebook]
Doing "ipython notebook" popped an error for which the solution is "pip install jupyter"
That popped an error for which the solution is "pip inistall path.py"
Now, ipython notebook does exactly the same thing as when running py27.
No cigar (yet).

**Comment by scottdraves** [comment] 2016-01-29 19:28
OK this is solved for Windows and Mac by documenting this package in our online installation instructions: https://github.com/twosigma/beaker-notebook-www/commit/ebdb4667ac323502defed616bab45a2bff4f5061

It might be needed for linux and docker, but that's a different fix so I opened another issue for that.

**Closed as completed by scottdraves** 2016-01-29 19:28 UTC
