### ISSUE TITLE
Editing categories occasionally fails on save

### ISSUE THREAD

**Issue by melmac48** [twosigma/beakerx#2638] opened 2015-10-07 13:51 UTC
In the publication server, as an admin editing the text for a category, when I click Save, nothing happens. I haven't been able to find reliable repro steps. 
Console output from the last time this happened:

```
TypeError: Cannot set property 'Sortable1444224775733' of undefined
    at new a (publications_vendor.js:9684)
    at Object.create (publications_main.js:806)
    at publications_main.js:3116
    at Scope.$emit (beakerVendor.js:47650)
    at publications_main.js:4071
    at beakerVendor.js:49039
    at completeOutstandingRequest (beakerVendor.js:39033)
    at beakerVendor.js:39347
```

**Comment by sethkrasnianski** [comment] 2015-10-13 21:29
Hey @melmac48, have you seen this since filing the issue? Were you able to isolate some steps to reproduce it?

**Comment by melmac48** [comment] 2015-10-13 22:29
I see it all the time on prod. I'll try to repro on staging

**Comment by ildipo** [comment] 2015-10-20 19:50
This was highly likely related to datomic death. Since it seems to be solved I'm closing it.

**Closed as completed by ildipo** 2015-10-20 19:50 UTC
Labels: Bug, Publications

**Comment by sethkrasnianski** [comment] 2015-10-20 20:01
:+1:
