### ISSUE TITLE
Inconsistent/missing output with iPython

### ISSUE THREAD

**Issue by psmaragdis** [twosigma/beakerx#2467] opened 2015-09-23 15:29 UTC
I'm having some trouble with output objects being overwritten in iPython Beaker notebooks. For example the following code snippet will only show the second figure and delete the first one after briefly showing it:

`figure(), plot( linspace( 0, -1)), title( 'Figure 1')`
`figure(), plot( linspace( 0,  1)), title( 'Figure 2')`

This could also be seen as a feature, meaning that I can create dynamically updating plots, but when opening a new figure I would have expected the old plot to persist and not get replaced.

Along the same lines, and more worryingly, the following code produces a different output every time it is run. It sometimes shows one player, sometimes two, but never three or all four, with the first ones being overwritten in the output:

`from IPython.display import display, Audio`
`print "sound 1", display( Audio( data=sin( 100*linspace( 0, 2*pi, 8000)), rate=8000))`
`print "sound 2", display( Audio( data=sin( 200*linspace( 0, 2*pi, 8000)), rate=8000))`
`print "sound 3", display( Audio( data=sin( 300*linspace( 0, 2*pi, 8000)), rate=8000))`
`print "sound 4", display( Audio( data=sin( 400*linspace( 0, 2*pi, 8000)), rate=8000))`

If I add a 1 second pause between these calls then only the last audio player is shown. If I remove the print statements all four are shown. So there seems to be a timing threshold after which previous output objects are replaced.

Just as before, being able to replace outputs can be a desirable trait, but I would have preferred to have control on which outputs are expendable and which should persist.

This is all on a Mac running the latest release version (and also the prerelease).

**Comment by scottdraves** [comment] 2015-09-23 15:31
Thanks for the detailed report Paris, much appreciated.
We'll get right on this.

**Comment by scottdraves** [comment] 2015-09-23 18:45
OK, looks like this has already been fixed.  I get this reliably from master: https://pub.beakernotebook.com/#/publications/5602f1b7-21e1-43e6-ab6c-19b8b72019a9?fullscreen=true

and i can confirm that with 1.3.4 I see the same bug that you do.

1.4 will be released at the end of the month, or you can get a prerelease:
http://beakernotebook.com/downloads

**Comment by psmaragdis** [comment] 2015-10-05 20:30
The problem seems to persist in 1.4 as well (albeit in a different form).

For example it the following code I get an audio player and a figure (ignore the error in the audio player, it's because I don't give it any data):

```
from IPython.display import display, Audio

display( Audio( [1], rate=8000))
subplot( 1, 2, 1), plot( [0,1])

#display( Audio( [1], rate=8000))
#subplot( 1, 2, 2), plot( [0,1])
```

Case 1: As it, it will present an audio player and a plot.

Case 2: If I add a  `time.sleep(.5)` between the audio player and the plot lines, only the plot appears. The expected behavior would be to show both.

Case 3: If I uncomment the last two lines, neither of the requested audio players appear (regardless of the existence of a sleep statement or not). The expected behavior would be to see two audio players and two plots.

In the latter cases, the audio players are momentarily visible, but they get overwritten by the plots when they are drawn.

**Comment by scottdraves** [comment] 2015-10-05 20:32
Thanks for your persistence reporting bugs :)  I'll look at this soon.

**Comment by scottdraves** [comment] 2015-10-11 17:56
<img width="466" alt="screen shot 2015-10-11 at 1 53 32 pm" src="https://cloud.githubusercontent.com/assets/963093/10418116/bf800a26-701f-11e5-999c-d41f7184c80c.png">

just got this on master.  the slider flashed & was replaced by the graph.

**Comment by alice-kroch** [comment] 2015-11-11 15:50
Hello, @psmaragdis . Please, try to run your tests on [this](https://www.dropbox.com/s/q5gvl2pqvko2yrc/Beaker%2011-11-15%2C%2017.51.xcarchive.zip?dl=0) dist

**Comment by psmaragdis** [comment] 2015-11-11 17:32
I can't seem to get the web browser to connect to this binary. Any idea why?

I exported as a Mac Application, but when launch it and go to 127.0.0.1:8801/beaker/ there's nothing to load (unlike other beaker binaries which present me with the initial page)

**Comment by alice-kroch** [comment] 2015-11-12 07:53
@psmaragdis, you have to perform next steps to launch the application:
1. open xcarchive in Finder
2. right click -> choose Show Package Contents
3. go to Products -> Applications
4. dbl click on Beaker application - it should present page in browser

**Comment by psmaragdis** [comment] 2015-11-12 19:39
It looks like this build is missing the jre files in the resources (hence not launching).

**Comment by alice-kroch** [comment] 2015-11-13 08:51
Have you opened http://127.0.0.1:8801/beaker/#/control in browser after steps above?

**Comment by psmaragdis** [comment] 2015-11-13 16:48
Looks like it was a problem with that one machine I was running it on. It launches, but it still doesn't behave predictably. The example with the four sound players at the start of the thread is fine, but if do:

```
figure(), plot( linspace( 0, -1)), title( 'Figure 1')
figure(), plot( linspace( 0, 1)), title( 'Figure 2')
```

I only get the second figure to show but not the first. If I do:

```
from IPython.display import display, Audio
figure(), plot( linspace( 0, -1)), title( 'Figure 1')
print "sound 1", display( Audio( data=sin( 100*linspace( 0, 2*pi, 8000)), rate=8000))
figure(), plot( linspace( 0, 1)), title( 'Figure 2')
print "sound 2", display( Audio( data=sin( 200*linspace( 0, 2*pi, 8000)), rate=8000))
```

I sometimes get both figures, most of the time I get the second figure only, but I never get the sound players (the briefly show up and then the output is cleared for the second figure).

If I add `time.sleep(1)` between all the lines I get the first sound player to show up, then it gets erased and the second sound player renders, then the second player gets erased, and then I get both figures.

**Closed as completed** 2017-03-29 21:23 UTC
Labels: Bug, Kernel

**Comment by psmaragdis** [comment] 2017-03-30 04:02
Just to verify, has this been resolved?

**Comment by scottdraves** [comment] 2017-03-30 12:41
it is no longer relevant due to http://us3.campaign-archive1.com/?u=d05838b85c905bc618b25e5a9&id=bf9c4bb414&e=49f86b7c29
