### ISSUE TITLE
%import magic breaks global variables

### ISSUE THREAD

**Issue by altavir** [twosigma/beakerx#5961] opened 2017-09-11 09:12 UTC
Like that:

```Groovy
a = 2
```

>   2

```Groovy
%import static java.lang.Math.PI
```
```Groovy
a*PI
```
>    groovy.lang.MissingPropertyException: No such property: a for class: script15051208463782932642
>    	at script15051208463782932642.run(script15051208463782932642.groovy:1)
>    	at com.twosigma.beakerx.groovy.evaluator.GroovyCodeRunner.run(GroovyCodeRunner.java:71)

I do not know how imports are implemented, but probably you create new shell instance with new compilation customization. In that case, you have to copy bindings content into new shell.

**Comment by scottdraves** [comment] 2017-09-11 15:02
confirmed.  thx for the report, i think your diagnosis is correct.
in the meantime, the workaround would be to run all %imports first.

**Comment by altavir** [comment] 2017-09-11 15:11
Done it already. Copping the context should pretty simple. You do not even need to clone it since it is stored in the separate `Binding` variable which could be passes to shell constructor.

**Comment by scottdraves** [comment] 2017-09-11 15:37
Do you mean you have code that fixes it?  Would be awesome if you could make a PR...

**Comment by altavir** [comment] 2017-09-11 16:23
Just looked through the code. It is implemented in a slightly different way, You do not use the shell object explicitly, instead you create a separate script for each cell (script parser creates the shell under the hood). In my experience this way you loose performance, but it is probably the best solution for notebook since you do not know what cell to expect next.

The problem is probably in [this line](https://github.com/twosigma/beakerx/blob/73ac34418eeed06df280b774dc51d44857dd5730/kernel/groovy/src/main/java/com/twosigma/beakerx/groovy/evaluator/GroovyWorkerThread.java#L69). It flushes the whole binding on classloader reset. One can try to just comment it, but I do not know why it was done in the first place, so I do not know if it will break anything.

**Comment by lmitusinski** [comment] 2018-07-16 13:03
This one seems to be fixed with:
https://github.com/twosigma/beakerx/issues/5965

**Closed as completed** 2018-07-17 20:47 UTC
Labels: Bug, Kernel
