### ISSUE TITLE
CSVPlotReader doesn't parse Strings correctly, instead returning "NAN"

### ISSUE THREAD

**Issue by pbuckley4192** [twosigma/beakerx#6106] opened 2017-10-10 09:12 UTC
Example DataSet (In zip due to github not allowing csv)
[Make Model Data 2016.zip](https://github.com/twosigma/beakerx/files/1371232/Make.Model.Data.2016.zip)

In the field "VehicleModel" any models containing a string return NAN

![bug](https://user-images.githubusercontent.com/1648634/31378532-864c265e-ada3-11e7-92e6-c065d5c6ed27.PNG)

**Comment by scottdraves** [comment] 2017-10-10 14:22
Thanks for the report.  The CSVPlotReader is really just intended to be good enough to load the tables we use for our documentation.  For real work I recommend loading a package like TableSaw (see the tutorial).  That said, this is probably easy to fix and we will look into it.

**Comment by scottdraves** [comment] 2017-10-10 14:47
Hm, I can't reproduce this.  Can you show the code you used?
![screen shot 2017-10-10 at 10 46 21 am](https://user-images.githubusercontent.com/963093/31392874-5a95d41a-ada8-11e7-936d-dba472c64492.png)

**Comment by pbuckley4192** [comment] 2017-10-11 08:10
![image](https://user-images.githubusercontent.com/1648634/31428809-04297494-ae64-11e7-8b4d-a9925fff280d.png)

**Comment by jpallas** [comment] 2017-10-11 17:51
Depending on how you look at it, this may be a TableDisplay bug.  CsvPlotReader doesn't have any notion of schema, so it produces values for VehicleModel that are either integers or strings, depending on the text.  A BMW 318 has a integer value for the model, while a BMW 318I has a string value.  TableDisplay, I think, infers a schema from the first row.  So, if the first value for a column happens to be numeric, it expects them all to be numeric and non-numeric values display as NaN.  

I'm not actually clear on whether this is happening on the Java side or the JavaScript side, to be honest.

**Comment by jmsdnns** [comment] 2017-11-29 07:36
I am able to reproduce this.

I wrote some python to walk the CSV and print any values in that column that aren't a number and sure enough they're strings.

I decided to test @jpallas's type inference theory and he is correct. I moved a line that has a string value in that column to the first line of the CSV's data and then the display worked correctly.

![screenshot from 2017-11-29 02-38-07](https://user-images.githubusercontent.com/7950614/33363422-5258da0e-d4ae-11e7-908e-faf2e76721b0.png)

**Comment by scottdraves** [comment] 2017-11-29 21:02
OK cool.  The CSVPlotReader class looks pretty weak, in fact it handles only time and number columns.  It should be rewritten and maybe even renamed so it's just our general CSV reader, not specific to plots.

**Comment by jmsdnns** [comment] 2017-11-30 06:46
## CsvPlotReader

The code starts with `CsvPlotReader.read()` processing the csv. This function reads each value in each in each row and attempts to convert it to a number while falling back to strings. One exception is that a column called `date` is parsed with a date converter.

The converted values are stored in a `List<Map<String, Object>>` - a list of rows where the column name maps to some `Object`.

No type information is lost yet.

## TableDisplay

That data is given as an argument to TableDisplay's constructor, which looks like this (_with irrelevant parts removed_):

```java
public TableDisplay(Collection<String, Object>> v, BeakerObjectConverter serializer) {
  super();
  ...
  columns = new ArrayList<>();

  for(each row) {
    for(each col) {
      ...
      if (!columns.contains(col)) {
        columns.add(c);
        String n = e.getValue() != null ? e.getValue().getClass().getName() : "string";
        classes.add(serializer.convertType(n));
      }
    }
  }
  ...
}
```

We see that the first row populates `columns` and `classes`. Both of these values are passed as the `columnNames` and `types` values to `TableDisplaySerializer` and is used as a type for the whole column.

## Fixing It

Loop across each row and visit the data in any columns not already marked as strings. Run a type check on the value to see if the column's type is still valid. If the type check fails, we could fail backwards into more general types with `String` acting as a last-resort.

If this sounds good, I will start implementing it.

**Comment by scottdraves** [comment] 2017-11-30 12:46
SGTM

**Comment by scottdraves** [comment] 2017-11-30 13:57
would this help? https://commons.apache.org/proper/commons-csv/

**Comment by jmsdnns** [comment] 2017-11-30 14:13
Looking into it.

**Comment by jmsdnns** [comment] 2017-12-02 00:33
Discussed with @scottdraves that the last commit solves this issue. My commit comments hints at the column order being incorrect relative to the CSV. That will be handled in a different issue.

**Closed as completed** 2017-12-02 02:53 UTC
